{
 "title": "Netology",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Filesystem space available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=\"xfs\",instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "Filesystem free bytes"
    }
   ]
  },
  {
   "title": "Memory Free/Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"})",
     "legendFormat": "Memory Free"
    },
    {
     "expr": "avg(node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"})",
     "legendFormat": "Memory Available"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{}[1m]))",
     "legendFormat": "CPULA 1"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{}[1m]))",
     "legendFormat": "CPULA 5"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{}[1m]))",
     "legendFormat": "CPULA 15"
    }
   ]
  },
  {
   "title": "Утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  }
 ]
}